"use client";
import { createContext, useContext, useState } from "react";
import { PRESET_AVATARS } from "@/lib/avatars";

export const Button = ({ variant="primary", className="", ...props }) => <button className={`btn btn-${variant} ${className}`} {...props} />;
export const Card = ({ className="", ...props }) => <section className={`card ${className}`} {...props} />;
export const Input = ({ className="", ...props }) => <input className={`field ${className}`} {...props} />;
export const Textarea = ({ className="", ...props }) => <textarea className={`field min-h-28 resize-y ${className}`} {...props} />;
export const Badge = ({ children, className="" }) => <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold ${className}`}>{children}</span>;
export const Avatar = ({ name="", src, url, className="", size="md" }) => {
  const avatarUrl = src || url;
  const sizeClasses = { sm: "h-6 w-6 text-xs", md: "h-9 w-9 text-xs", lg: "h-12 w-12 text-sm", xl: "h-16 w-16 text-3xl" };
  const sClass = sizeClasses[size] || sizeClasses.md;
  const preset = PRESET_AVATARS.find(a => a.id === avatarUrl);
  if (preset) return <span className={`inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-gradient-to-br ${preset.color} ${sClass} ${className}`} title={name}>{preset.emoji}</span>;
  return <span className={`inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-[var(--surface)] font-semibold border border-white/5 ${sClass} ${className}`} title={name}>{avatarUrl ? <img src={avatarUrl} alt="" className="h-full w-full object-cover" /> : name.slice(0,1).toUpperCase() || "?"}</span>;
};
export { AvatarPicker } from "./AvatarPicker";
export const Alert = ({ title, children, variant="info" }) => <div role="alert" className={`card border-l-4 p-4 ${variant === "error" ? "border-l-[var(--danger)]" : variant === "success" ? "border-l-[var(--success)]" : "border-l-[var(--accent)]"}`}><p className="font-semibold">{title}</p>{children && <p className="mt-1 text-sm text-muted">{children}</p>}</div>;
export const Checkbox = (props) => <input type="checkbox" className="h-4 w-4 accent-[var(--accent)]" {...props} />;
export const Radio = (props) => <input type="radio" className="h-4 w-4 accent-[var(--accent)]" {...props} />;
export const Progress = ({ value=0 }) => <div className="h-2 overflow-hidden rounded-full bg-[var(--surface)]" role="progressbar" aria-valuenow={value} aria-valuemin="0" aria-valuemax="100"><div className="h-full rounded-full bg-[var(--accent)]" style={{width:`${value}%`}} /></div>;
export const Spinner = () => <span aria-label="Loading" className="inline-block h-5 w-5 animate-spin rounded-full border-2 border-[var(--border)] border-t-[var(--accent)]" />;
export const Skeleton = ({ className="" }) => <div className={`animate-pulse rounded bg-[var(--surface)] ${className}`} />;
export const EmptyState = ({ title="Nothing here yet", children }) => <div className="card p-10 text-center"><h3 className="font-semibold">{title}</h3>{children && <p className="mt-2 text-sm text-muted">{children}</p>}</div>;
export const StatCard = ({ label, value, detail }) => <Card className="p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p>{detail && <p className="mt-2 text-xs text-accent">{detail}</p>}</Card>;
export const FeatureCard = ({ icon, title, children }) => <Card className="p-6"><div className="text-accent">{icon}</div><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{children}</p></Card>;
export const Tooltip = ({ label, children }) => <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-[var(--foreground)] px-2 py-1 text-xs text-[var(--background)] group-hover:block">{label}</span></span>;
export const Modal = ({ open, onClose, title, children }) => open ? <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-4" onMouseDown={onClose}><div className="card animate-in w-full max-w-md p-6" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} aria-label="Close dialog">×</button></div><div className="mt-4">{children}</div></div></div> : null;
const ToastContext=createContext(()=>{}); export const ToastProvider=({children})=>{const [toasts,setToasts]=useState([]); const show=(message,variant="info")=>{const id=Date.now();setToasts(t=>[...t,{id,message,variant}]);setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),3500)};return <ToastContext.Provider value={show}>{children}<div className="fixed bottom-4 right-4 z-[70] space-y-2">{toasts.map(t=><Alert key={t.id} title={t.message} variant={t.variant}/>)}</div></ToastContext.Provider>}; export const useToast=()=>useContext(ToastContext);
export const Tabs=({tabs,active,onChange})=><div role="tablist" className="flex gap-1 rounded-xl border p-1">{tabs.map(t=><button role="tab" aria-selected={active===t.value} key={t.value} onClick={()=>onChange(t.value)} className={`rounded-lg px-3 py-1.5 text-sm ${active===t.value?"bg-[var(--surface)] font-semibold":"text-muted"}`}>{t.label}</button>)}</div>;
export const Accordion=({items})=><div className="space-y-2">{items.map(i=><details key={i.title} className="card p-4"><summary className="cursor-pointer font-semibold">{i.title}</summary><p className="mt-3 text-sm text-muted">{i.content}</p></details>)}</div>;
export const Dropdown=({label,children})=>{const [open,setOpen]=useState(false);return <div className="relative inline-block"><button className="btn btn-secondary" onClick={()=>setOpen(!open)} aria-expanded={open}>{label}</button>{open&&<div className="card animate-in absolute right-0 z-30 mt-2 min-w-40 p-1">{children}</div>}</div>};
